# Generated by Django 4.2.7 on 2023-11-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='lang_id',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='page_id',
            new_name='page',
        ),
    ]
