# Generated by Django 4.2.7 on 2023-12-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_rename_lang_id_content_lang_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='lang',
            new_name='language',
        ),
    ]
