# Generated by Django 4.2.7 on 2023-12-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_rename_lang_content_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang',
            new_name='lang_name',
        ),
    ]
